# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  migrate:
    dotenv:
      - .env
    dir: ./backend
    cmds:
      - python manage.py makemigrations
      - python manage.py migrate
