@startuml entidades

class Usuario {

}

class Contrato {
    usuario: Usuario
    valido_ate: date
    limite_pdvs: int

}

Contrato o-- Usuario

class PDV {
    contrato: Contrato
    nome: string
    limite_credito_padrao: decimal
    saldo_debitos: decimal
}

PDV o-- Contrato

class Cliente {
    +cpf: string
    nome: string
    telefone: string
}

class Venda {
    pdv: PDV
    cliente: Cliente
    data: date
    valor_original: decimal
}

enum TipoMovimento {
    VENDA
    PAGAMENTO
    ACRESCIMO
    DESCONTO
}
class Movimento{
    venda: Venda
    usuario: Usuario
    tipo: TipoMovimento
    data: date
    descricao: string
    valor: decimal
}

Movimento -- TipoMovimento
Movimento -- Venda
Movimento -- Usuario

Venda o-- PDV
Venda o-- Cliente


@enduml
