# Generated by Django 5.0 on 2023-12-08 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={"verbose_name": "contrato", "verbose_name_plural": "contratos"},
        ),
        migrations.AddField(
            model_name="contract",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_by_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
            preserve_default=False,
        ),
    ]
