# Generated by Django 5.0 on 2023-12-09 00:04

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_client_options_alter_pos_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[app.models.positive_value],
                verbose_name="Valor",
            ),
        ),
        migrations.AlterField(
            model_name="salemovement",
            name="description",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="salemovement",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[app.models.positive_value],
                verbose_name="Valor",
            ),
        ),
    ]
