# Generated by Django 5.0 on 2023-12-09 09:18

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_sale_value_alter_salemovement_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[app.models.positive_value],
                verbose_name="Valor",
            ),
        ),
    ]
