# Generated by Django 5.0 on 2023-12-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_sale_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="allowed_pos",
            field=models.ManyToManyField(to="app.pos"),
        ),
    ]
