# Generated by Django 5.0 on 2024-01-11 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_userextra"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userextra",
            name="id",
        ),
        migrations.AlterField(
            model_name="userextra",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
